#!/bin/sh
#
# $FreeBSD$
#

PREFIX=${PKG_PREFIX}
if [ "$2" != "POST-DEINSTALL" ]; then
	exit 0
fi

rm ${PREFIX}/bin/mangband
rm ${PREFIX}/bin/mangclient

MALIB=${PREFIX}/share/games/mangband

rm -fR ${MALIB}/*
rmdir ${MALIB}

exit 0
