#!/bin/bash
# Runserv, by Chris Atenasio
ulimit -c unlimited

while :; do
	nohup ./mangband -Z >nohup.out 2>&1   # Needed so we get core files!
	if [ -f core ] ; then
		mv core cores/`/bin/date +"%Y.%m.%d.%I.%M.%S"`
	fi
	mv nohup.out nohup.`/bin/date +"%Y.%m.%d.%I.%M.%S"`
	mv lib/data/mangband.log lib/data/mangband.`/bin/date +"%Y.%m.%d.%I.%M.%S"`
done
