#!/bin/bash
# Originally by Chris Atenasio
# Updated by the MAngband Project Team

GAME_DIR=./

cd $GAME_DIR
ulimit -c unlimited

while :; do
	nohup $GAME_DIR/mangband >nohup.out 2>&1   # Needed so we get core files!
        exitcode=$?
        stamp=`date`;
        echo "$stamp Server exited with exit code $exitcode" >> nohup.out
	if [ -f core ] ; then
		mv core cores/`/bin/date +"%Y.%m.%d.%I.%M.%S"`
	fi
	mv nohup.out logs/nohup.`/bin/date +"%Y.%m.%d.%I.%M.%S"`
	sleep 5
done
