Name:       %{name}
Summary:      Free online multiplayer real-time roguelike game
Version:       %{version}
Release:      %{release}
Group:       Amusements/Games
URL:       http://www.mangband.org
Source:       %{name}-%{version}.tar.gz
License:        Public Use
#Requires:       SDL, libX11, ncurses   
#BuildRequires:  SDL-devel, libX11-devel, ncurses-devel
Buildroot:      %{_tmppath}/%{name}-buildroot

%description
 MAngband is a free online multiplayer real-time roguelike game,
 derived from the single player game Angband.

%package -n mangclient-sdl
Summary:      SDL client
Requires: SDL
BuildRequires:  SDL-devel
%description -n mangclient-sdl
SDL version of client.

%package -n mangclient-x11
Summary:      X11 client
Requires: libX11
BuildRequires:  libX11-devel
%description -n mangclient-x11
X11 version of client.

%package -n mangclient-gcu
Summary:      GCU client
Requires: ncurses
BuildRequires:  ncurses-devel
%description -n mangclient-gcu
GCU version of client (ncurses).

%prep -q
%setup -q

%build
cd src
CFLAGS="$RPM_OPT_FLAGS"
./configure --prefix=%{_prefix} --libdir=%{_libdir}
make

%clean
rm -rf $RPM_BUILD_ROOT

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/{/etc,/usr/bin,/usr/games}
install -m755 $RPM_BUILD_DIR/%{name}-%{version}/mangband $RPM_BUILD_ROOT/usr/bin
install -m755 $RPM_BUILD_DIR/%{name}-%{version}/mangclient $RPM_BUILD_ROOT/usr/bin
install -m644 $RPM_BUILD_DIR/%{name}-%{version}/mangband.cfg $RPM_BUILD_ROOT/etc/mangband.cfg
cp -R $RPM_BUILD_DIR/%{name}-%{version}/lib $RPM_BUILD_ROOT/usr/games/mangband
rm $RPM_BUILD_ROOT/usr/games/mangband/file/delete.me
rm $RPM_BUILD_ROOT/usr/games/mangband/help/delete.me
rm $RPM_BUILD_ROOT/usr/games/mangband/data/scores.raw

%post
MALIB=/usr/games/mangband
#echo "[MAngband]" > /root/.mangrc
echo "LibDir ${MALIB}/" >> /root/.mangrc
echo "# RPM Hacks" >> /etc/mangband.cfg
echo "EDIT_DIR = \"${MALIB}/edit\"" >> /etc/mangband.cfg
echo "SAVE_DIR = \"${MALIB}/save\"" >> /etc/mangband.cfg
echo "DATA_DIR = \"${MALIB}/data\"" >> /etc/mangband.cfg

%files
%defattr(-,games,games)
/usr/games/mangband
%attr(-,root,root)
%config(noreplace) /etc/mangband.cfg
%defattr(755,root,root)
/usr/bin/mangband

%files -n mangclient-sdl
%defattr(-,games,games)
/usr/games/mangband
%attr(755,root,root)
/usr/bin/mangclient

%files -n mangclient-x11
%defattr(-,games,games)
/usr/games/mangband
%attr(755,root,root)
/usr/bin/mangclient

%files -n mangclient-gcu
%defattr(-,games,games)
/usr/games/mangband
%attr(755,root,root)
/usr/bin/mangclient


%changelog
* Sun Apr 27 2009 %{packager} %{version}-%{release}
- .spec-file assembled

