name: ci-cd
on: [push]
jobs:
  win64:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            automake
            autoconf
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL
            mingw-w64-x86_64-SDL_ttf
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
      - name: "Build SDL1.2 client"
        shell: msys2 {0}
        run: |
          ./autogen.sh -n
          ./configure --with-sdl --without-sdl2 --without-gcu --enable-win
          make clean
          make mangclient
          cp mangclient.exe mangclient-sdl.exe
      - name: "Build SDL2 client"
        shell: msys2 {0}
        run: |
          ./autogen.sh -n
          ./configure --with-sdl --without-sdl2 --without-gcu --enable-win
          make clean
          make mangclient
          cp mangclient.exe mangclient-sdl.exe
      - name: "Build WIN32 client and server"
        shell: msys2 {0}
        run: |
          ./autogen.sh -n
          ./configure --without-sdl --without-sdl2 --without-gcu --enable-win
          make clean
          make
      - name: "nuget InnoSetup"
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - run: nuget install Tools.InnoSetup -Version 6.2.0
      - shell: cmd
        run: |
          ISCC.exe "dist\exe\installer-client-win.iss" "/Q"
          ISCC.exe "dist\exe\installer-server-win.iss" "/Q"
      - uses: actions/upload-artifact@v2
        with:
          name: mangband-client-setup
          path: mangband-client-setup-v1.5.3.exe
      - uses: actions/upload-artifact@v2
        with:
          name: mangband-server-setup
          path: mangband-server-setup-v1.5.3.exe
  upload_win64:
    runs-on: ubuntu-latest
    needs: win64 
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: develop-win64
          tag: develop-win64
          files: |
            mangband-client-setup-v1.5.3.exe
            mangband-server-setup-v1.5.3.exe

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: false
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build connectedCheck assembleDebug assembleRelease
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Run tests
        run: ./gradlew test
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
