name: msys2-build
on: [push]
jobs:
  win64:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            automake
            autoconf
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL
            mingw-w64-x86_64-SDL_ttf
      - shell: msys2 {0}
        run: |
          ./autogen.sh -n
          ./configure
          make
