name: msys2-build
on: [push]
jobs:
  win64:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            automake
            autoconf
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL
            mingw-w64-x86_64-SDL_ttf
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
      - name: "Build SDL1.2 client"
        shell: msys2 {0}
        run: |
          ./autogen.sh -n
          ./configure --with-sdl --without-sdl2 --without-gcu --enable-win
          make clean
          make
          cp mangclient.exe mangclient-sdl.exe
      - name: "Build SDL2 client"
        shell: msys2 {0}
        run: |
          ./autogen.sh -n
          ./configure --with-sdl --without-sdl2 --without-gcu --enable-win
          make clean
          make
          cp mangclient.exe mangclient-sdl.exe
      - name: "Build WIN32 client"
        shell: msys2 {0}
        run: |
          ./autogen.sh -n
          ./configure --without-sdl --without-sdl2 --without-gcu --enable-win
          make clean
          make
      - name: "nuget InnoSetup"
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - run: nuget install Tools.InnoSetup -Version 6.2.0
      # Prepare installers
      - shell: cmd
        run: |
          ISCC.exe "dist\exe\installer-client-win.iss" "/Q"
          ISCC.exe "dist\exe\installer-server-win.iss" "/Q"
      # Release
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: develop-win64
          files: |
            mangband-client-setup-v1.5.3.exe
            mangband-server-setup-v1.5.3.exe
